development:
  perform_authentication: true
  S3_BUCKET: guycode-assets
  AWS_ACCESS_KEY_ID: AKIAILPDC2MIASCCK22Q
  AWS_SECRET_ACCESS_KEY: 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

test:
  perform_authentication: true
  S3_BUCKET: guycode-assets
  AWS_ACCESS_KEY_ID: AKIAILPDC2MIASCCK22Q
  AWS_SECRET_ACCESS_KEY: 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

production:
  perform_authentication: true
  S3_BUCKET: guycode-assets
  AWS_ACCESS_KEY_ID: AKIAILPDC2MIASCCK22Q
  AWS_SECRET_ACCESS_KEY: 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