# ENV['S3_BUCKET_NAME'] = guycode-assets
# ENV['AWS_ACCESS_KEY'] = AKIAILPDC2MIASCCK22Q
# ENV['AWS_SECRET_ACCESS'] = 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

# development:
#   perform_authentication: true
#   S3_BUCKET_NAME: guycode-assets
#   AWS_ACCESS_KEY: AKIAILPDC2MIASCCK22Q
#   AWS_SECRET_ACCESS: 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

# test:
#   perform_authentication: true
#   S3_BUCKET_NAME: guycode-assets
#   AWS_ACCESS_KEY: AKIAILPDC2MIASCCK22Q
#   AWS_SECRET_ACCESS: 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

# production:
#   perform_authentication: true
#   S3_BUCKET_NAME: guycode-assets
#   AWS_ACCESS_KEY: AKIAILPDC2MIASCCK22Q
#   AWS_SECRET_ACCESS: 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